In [283]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [284]:
df = sns.load_dataset('titanic')

In [285]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [286]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [287]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [288]:
df.drop(["deck", "embark_town", "alive", "class", "who", "adult_male"], axis=1, inplace=True, errors='ignore')


In [289]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [290]:
df['age'].fillna(df['age'].mean(), inplace=True)

In [291]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [292]:
df.dropna(subset=["embarked"], inplace=True)


In [293]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


In [294]:
from sklearn.preprocessing import LabelEncoder

In [295]:
le = LabelEncoder()

In [296]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [297]:
df['sex'] = le.fit_transform(df['sex'])

In [298]:
df.head()

survived  pclass  sex   age  sibsp  parch     fare embarked  alone
0         0       3    1  22.0      1      0   7.2500        S  False
1         1       1    0  38.0      1      0  71.2833        C  False
2         1       3    0  26.0      0      0   7.9250        S   True
3         1       1    0  35.0      1      0  53.1000        S  False
4         0       3    1  35.0      0      0   8.0500        S   True

In [299]:
df['emabarked'] = le.fit_transform(df['embarked'])


In [300]:
df.head()

survived  pclass  sex   age  sibsp  parch     fare embarked  alone  \
0         0       3    1  22.0      1      0   7.2500        S  False   
1         1       1    0  38.0      1      0  71.2833        C  False   
2         1       3    0  26.0      0      0   7.9250        S   True   
3         1       1    0  35.0      1      0  53.1000        S  False   
4         0       3    1  35.0      0      0   8.0500        S   True   

   emabarked  
0          2  
1          0  
2          2  
3          2  
4          2

In [301]:
# Drop the original 'embarked' column and convert 'alone' to int
df = df.drop('embarked', axis=1)
df['alone'] = df['alone'].astype(int)
df = df.astype(int)

In [302]:
df.head()


survived  pclass  sex  age  sibsp  parch  fare  alone  emabarked
0         0       3    1   22      1      0     7      0          2
1         1       1    0   38      1      0    71      0          0
2         1       3    0   26      0      0     7      1          2
3         1       1    0   35      1      0    53      0          2
4         0       3    1   35      0      0     8      1          2

In [303]:
from sklearn.model_selection import train_test_split

In [304]:
X = df.drop("survived", axis=1)
y = df['survived']

In [305]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [306]:
from sklearn.linear_model import LogisticRegression

In [307]:
model = LogisticRegression()


In [308]:
model.fit(X_train,y_train)

LogisticRegression()

In [309]:
y_pred = model.predict(X_test)

In [310]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [311]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [312]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [313]:
accuracy_score(y_test, y_pred)

0.8033707865168539

In [314]:
confusion_matrix(y_test, y_pred)

array([[90, 19],
       [16, 53]])

In [315]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [316]:
df

survived  pclass  sex  age  sibsp  parch  fare  alone  emabarked
0           0       3    1   22      1      0     7      0          2
1           1       1    0   38      1      0    71      0          0
2           1       3    0   26      0      0     7      1          2
3           1       1    0   35      1      0    53      0          2
4           0       3    1   35      0      0     8      1          2
..        ...     ...  ...  ...    ...    ...   ...    ...        ...
886         0       2    1   27      0      0    13      1          2
887         1       1    0   19      0      0    30      1          2
888         0       3    0   29      1      2    23      0          2
889         1       1    1   26      0      0    30      1          0
890         0       3    1   32      0      0     7      1          1

[889 rows x 9 columns]

In [317]:
from sklearn.preprocessing import StandardScaler

In [318]:
scaler = StandardScaler()

In [319]:
X_scale_train = scaler.fit_transform(X_train)

In [320]:
X_scale_train

array([[-1.58410418, -1.40530972, -0.58667407, ...,  2.42752104,
         0.81076671,  0.58770431],
       [ 0.8122747 , -1.40530972, -0.05336323, ..., -0.35872483,
        -1.23340042, -1.95246446],
       [ 0.8122747 ,  0.71158691,  0.17519856, ..., -0.50108776,
         0.81076671,  0.58770431],
       ...,
       [-1.58410418, -1.40530972,  1.39419477, ..., -0.13501166,
         0.81076671,  0.58770431],
       [ 0.8122747 , -1.40530972, -0.66286134, ...,  0.04802639,
        -1.23340042,  0.58770431],
       [ 0.8122747 ,  0.71158691,  0.25138582, ..., -0.4807502 ,
         0.81076671,  0.58770431]], shape=(711, 8))

In [321]:
X_scale_test = scaler.transform(X_test)
X_scale_test

array([[ 0.8122747 ,  0.71158691, -0.12955049, ..., -0.50108776,
         0.81076671,  0.58770431],
       [-1.58410418, -1.40530972, -1.19617218, ...,  1.79705664,
        -1.23340042,  0.58770431],
       [ 0.8122747 , -1.40530972, -1.19617218, ..., -0.41973751,
        -1.23340042, -1.95246446],
       ...,
       [ 0.8122747 , -1.40530972,  0.63232214, ..., -0.01298629,
        -1.23340042,  0.58770431],
       [ 0.8122747 , -1.40530972,  0.25138582, ..., -0.33838727,
        -1.23340042,  0.58770431],
       [ 0.8122747 , -1.40530972, -1.95804481, ..., -0.31804971,
        -1.23340042,  0.58770431]], shape=(178, 8))

In [322]:
from sklearn.neighbors import KNeighborsClassifier

In [323]:
knn_model = KNeighborsClassifier(n_neighbors=  5)

In [324]:
knn_model.fit(X_scale_train, y_train)

KNeighborsClassifier()

In [325]:
y_pred_knn = knn_model.predict(X_scale_test)

In [326]:
accuracy_score(y_test, y_pred_knn)

0.7921348314606742

In [327]:
confusion_matrix(y_test, y_pred_knn)

array([[89, 20],
       [17, 52]])

In [328]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       109
           1       0.72      0.75      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.79      0.79      0.79       178



In [329]:
X_train

pclass  sex  age  sibsp  parch  fare  alone  emabarked
708       1    0   22      0      0   151      1          2
240       3    0   29      1      0    14      0          0
382       3    1   32      0      0     7      1          2
792       3    0   29      8      2    69      0          2
683       3    1   14      5      2    46      0          2
..      ...  ...  ...    ...    ...   ...    ...        ...
107       3    1   29      0      0     7      1          2
271       3    1   25      0      0     0      1          2
862       1    0   48      0      0    25      1          2
436       3    0   21      2      2    34      0          2
103       3    1   33      0      0     8      1          2

[711 rows x 8 columns]

In [330]:
from sklearn.naive_bayes import GaussianNB

In [331]:
nav_model = GaussianNB()

In [332]:
nav_model.fit(X_train,y_train)

GaussianNB()

In [333]:
y_pred_nav = nav_model.predict(X_test)

In [334]:
accuracy_score(y_test, y_pred_nav)

0.7752808988764045

In [335]:
confusion_matrix(y_test, y_pred_nav)

array([[84, 25],
       [15, 54]])

In [336]:
print(classification_report(y_test,y_pred_nav))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



In [337]:
from sklearn.tree import DecisionTreeClassifier

In [338]:
model_decTree = DecisionTreeClassifier(random_state=42)


In [339]:
model_decTree.fit(X_scale_train,y_train)

DecisionTreeClassifier(random_state=42)

In [340]:
y_pred_decTree = model_decTree.predict(X_scale_test)

In [341]:
y_pred_decTree = model_decTree.predict(X_scale_test)
accuracy_score(y_test, y_pred_decTree)

0.7921348314606742

In [342]:
confusion_matrix(y_test, y_pred_decTree)

array([[89, 20],
       [17, 52]])

In [343]:
print(classification_report(y_test,y_pred_decTree))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       109
           1       0.72      0.75      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.79      0.79      0.79       178



In [344]:
model_decTree.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [345]:
y_dt_pred = model_decTree.predict(X_test)

In [346]:
y_dt_pred = model_decTree.predict(X_test)
accuracy_score(y_test, y_dt_pred)

0.7921348314606742

In [347]:
confusion_matrix(y_test, y_dt_pred)

array([[88, 21],
       [16, 53]])

In [348]:
print(classification_report(y_test,y_dt_pred))

              precision    recall  f1-score   support

           0       0.85      0.81      0.83       109
           1       0.72      0.77      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.80      0.79      0.79       178



In [349]:
from sklearn.svm import SVC

In [350]:
from sklearn.svm import SVC

model_svm = SVC(kernel = 'rbf')

In [351]:
model_svm.fit(X_scale_train,y_train)

SVC()

In [352]:
y_pred_sv = model_svm.predict(X_scale_test)

In [353]:
accuracy_score(y_test, y_pred_sv)

0.8146067415730337

In [354]:
confusion_matrix(y_test, y_pred_sv)

array([[91, 18],
       [15, 54]])

In [355]:
print(classification_report(y_test,y_pred_sv))

              precision    recall  f1-score   support

           0       0.86      0.83      0.85       109
           1       0.75      0.78      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.81       178
weighted avg       0.82      0.81      0.82       178

